name: catatbeli
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0

  cupertino_icons: ^1.0.2
  drift: ^2.2.0
  path_provider: ^2.0.1
  sqlite3_flutter_libs: ^0.5.0
  equatable: ^2.0.3
  flutter_typeahead: ^4.3.8
  barcode_scan2: ^4.4.0
  camera: ^0.10.6
  intl: ^0.18.0
  flutter_keyboard_visibility: ^5.4.0
  url_launcher: ^6.0.12
  flutter_file_dialog: ^3.0.0
  bitsdojo_window: ^0.1.5
  file_picker: ^8.0.3
  # msix: ^3.6.2
  shared_preferences: ^2.0.15
  auto_size_text: ^3.0.0
  excel: ^4.0.3
  formz: ^0.7.0
  flex_color_scheme: ^7.1.2
  google_fonts: ^6.2.1
  month_picker_dialog: ^2.0.2
  syncfusion_flutter_charts: ^25.2.3 
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  mime: ^1.0.6
  currency_text_input_formatter: ^2.2.8
  http: ^1.3.0
  flutter_dotenv: any 
  dio: ^5.8.0+1
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.3
  # flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  drift_dev: ^2.2.0+1
  build_runner: ^2.0.5

flutter_icons:
#terminal: dart run flutter_launcher_icons:generate
  android: true
  image_path: "lib/assets/buku.png"
  # web: true
  # windows: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: OpenSans
     fonts:
       - asset: assets/OpenSans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
